//
// Copyright (c) 2016-2018 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//

=== Major changes to previous versions



* Changes in 2.0
** Refactoring of Counters, as the old `@Counted` was misleading in practise.
*** Counters via `@Counted` are now always monotonic, the `monotonic` attribute is gone.
The `Counted` interface lost the `dec()` methods.
*** Former non-monotonic counters are now `@ConcurrentGauge` and also in the output reported as gauges.
*** See <<migration-hint-to-20, Migration hints>> about migration of applications using MicroProfile Metrics.
** Removed unnecessary `@InterceptorBinding` annotation from `org.eclipse.microprofile.metrics.annotation.Metric`.
** Removed deprecated `org.eclipse.microprofile.metrics.MetricRegistry.register(String name, Metric, Metadata)`
** `Metadata` is now immutable and built via a `MetadataBuilder`.

* Changes in 1.1
** Improved TCK
** `org.eclipse.microprofile.metrics.MetricRegistry.register(String name, Metric, Metadata)` is deprecated.
Use `org.eclipse.microprofile.metrics.MetricRegistry.register(Metadata, Metric)` instead, where `Metadata`
already has a field for the name.
** Global tags are now supplied via the means of MicroProfile Config (the env variable is still valid).
** Annotations and `Metadata` can now have a flag `reusable` that indicates that the metric name can be registered
more than once. Default is `false` as in Metrics 1.0. See <<reusing_of_metrics>>.
